<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('880', '/uploads/userup/107/13310554a-C24.doc');
$maNum = 1;
$myaddons[$maNum] = array('881', '/uploads/userup/107/1331055627-2247.doc');
$maNum = 2;
$myaddons[$maNum] = array('882', '/uploads/userup/107/1331055Y0-PS.txt');
$maNum = 3;
$myaddons[$maNum] = array('883', '/uploads/userup/107/1331055955-V31.txt');
$maNum = 4;
$myaddons[$maNum] = array('884', '/uploads/userup/107/133105PD-60O.txt');
$maNum = 5;
