<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('388', '/uploads/userup/62/12Y026263-5S6.ppt');
$maNum = 1;
$myaddons[$maNum] = array('389', '/uploads/userup/62/12Y02M04-54Z.doc');
$maNum = 2;
$myaddons[$maNum] = array('390', '/uploads/userup/62/12Y02M15-9162.ppt');
$maNum = 3;
$myaddons[$maNum] = array('391', '/uploads/userup/1/12Y02R35-M45.doc');
$maNum = 4;
$myaddons[$maNum] = array('392', '/uploads/userup/1/12Y02R41-G30.doc');
$maNum = 5;
$myaddons[$maNum] = array('393', '/uploads/userup/1/12Y02R45-5F3.ppt');
$maNum = 6;
$myaddons[$maNum] = array('394', '/uploads/userup/1/12Y02R46-X18.doc');
$maNum = 7;
