<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('780', '/uploads/userup/1/12b3E244-M38.doc');
$maNum = 1;
$myaddons[$maNum] = array('781', '/uploads/userup/1/12b3E248-4P2.doc');
$maNum = 2;
$myaddons[$maNum] = array('782', '/uploads/userup/1/12b3E308-2Z8.doc');
$maNum = 3;
$myaddons[$maNum] = array('783', '/uploads/userup/1/12b3E316-aA.doc');
$maNum = 4;
$myaddons[$maNum] = array('784', '/uploads/userup/1/12b3E364-5210.doc');
$maNum = 5;
$myaddons[$maNum] = array('785', '/uploads/userup/1/12b3E4R-1260.doc');
$maNum = 6;
