<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('153', '/docshare/uploads/userup/8/12S2600C-4946.doc');
$maNum = 1;
$myaddons[$maNum] = array('154', '/docshare/uploads/userup/8/12S260118-3E7.doc');
$maNum = 2;
$myaddons[$maNum] = array('155', '/docshare/uploads/userup/8/12S2601R-5G0.doc');
$maNum = 3;
$myaddons[$maNum] = array('156', '/docshare/uploads/userup/8/12S260203-13K.doc');
$maNum = 4;
$myaddons[$maNum] = array('157', '/docshare/uploads/userup/8/12S260235-3V9.doc');
$maNum = 5;
$myaddons[$maNum] = array('158', '/docshare/uploads/userup/8/12S2602G-C30.doc');
$maNum = 6;
