<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('891', '/uploads/userup/107/1332MFQ-3057.doc');
$maNum = 1;
$myaddons[$maNum] = array('892', '/uploads/userup/107/1332MG57-X40.pdf');
$maNum = 2;
$myaddons[$maNum] = array('893', '/uploads/userup/107/1332MGS-4V1.pdf');
$maNum = 3;
$myaddons[$maNum] = array('894', '/uploads/userup/107/1332MH12-55c.pdf');
$maNum = 4;
$myaddons[$maNum] = array('895', '/uploads/userup/107/1332MI38-QU.doc');
$maNum = 5;
$myaddons[$maNum] = array('896', '/uploads/userup/107/1332M9129-1105.doc');
$maNum = 6;
