<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('769', '/uploads/userup/61/12b32C03-5544.pdf');
$maNum = 1;
$myaddons[$maNum] = array('770', '/uploads/userup/61/12b32FB-D46.pdf');
$maNum = 2;
$myaddons[$maNum] = array('771', '/uploads/userup/61/12b32H36-3444.pdf');
$maNum = 3;
$myaddons[$maNum] = array('772', '/uploads/userup/61/12b32J09-Kc.pdf');
$maNum = 4;
$myaddons[$maNum] = array('773', '/uploads/userup/61/12b32J21-UD.pdf');
$maNum = 5;
