<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('280', '/docshare/uploads/userup/8/12UR61S-1429.doc');
$maNum = 1;
$myaddons[$maNum] = array('281', '/docshare/uploads/userup/8/12UR61U-4I7.pdf');
$maNum = 2;
$myaddons[$maNum] = array('282', '/docshare/uploads/userup/8/12UR61V-1343.doc');
$maNum = 3;
$myaddons[$maNum] = array('283', '/docshare/uploads/userup/8/12UR61W-5356.pdf');
$maNum = 4;
$myaddons[$maNum] = array('284', '/docshare/uploads/userup/8/12UR61X-X22.pdf');
$maNum = 5;
