<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('275', '/docshare/uploads/userup/1/12U49E40-4127.doc');
$maNum = 1;
$myaddons[$maNum] = array('276', '/docshare/uploads/userup/1/12U4a031-5V5.doc');
$maNum = 2;
$myaddons[$maNum] = array('277', '/docshare/uploads/userup/1/12U4a049-E54.doc');
$maNum = 3;
$myaddons[$maNum] = array('278', '/docshare/uploads/userup/1/12U4a0Y-42B.doc');
$maNum = 4;
$myaddons[$maNum] = array('279', '/docshare/uploads/userup/1/12U4a122-5949.doc');
$maNum = 5;
