<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('627', '/uploads/userup/67/1293091024-N51.doc');
$maNum = 1;
$myaddons[$maNum] = array('628', '/uploads/userup/67/1293091028-53E.doc');
$maNum = 2;
$myaddons[$maNum] = array('629', '/uploads/userup/67/1293091029-2435.doc');
$maNum = 3;
$myaddons[$maNum] = array('630', '/uploads/userup/67/1293091038-3I0.doc');
$maNum = 4;
$myaddons[$maNum] = array('631', '/uploads/userup/67/1293091061-1924.doc');
$maNum = 5;
