<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('848', '/uploads/userup/102/132003V27-Yb.doc');
$maNum = 1;
$myaddons[$maNum] = array('849', '/uploads/userup/102/132003VX-5240.doc');
$maNum = 2;
$myaddons[$maNum] = array('850', '/uploads/userup/102/132003W04-2b4.doc');
$maNum = 3;
$myaddons[$maNum] = array('851', '/uploads/userup/102/1320039295-X51.doc');
$maNum = 4;
$myaddons[$maNum] = array('852', '/uploads/userup/102/1320039D2-S32.doc');
$maNum = 5;
$myaddons[$maNum] = array('853', '/uploads/userup/102/132003bQ-1M9.doc');
$maNum = 6;
