<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('360', '/uploads/userup/60/12X936034-10Z.ppt');
$maNum = 1;
$myaddons[$maNum] = array('361', '/uploads/userup/60/12X936136-X03.pdf');
$maNum = 2;
$myaddons[$maNum] = array('362', '/uploads/userup/60/12X93CJ-21D.pdf');
$maNum = 3;
$myaddons[$maNum] = array('363', '/uploads/userup/60/12X93D11-25D.pdf');
$maNum = 4;
$myaddons[$maNum] = array('364', '/uploads/userup/60/12X93K18-D08.pdf');
$maNum = 5;
$myaddons[$maNum] = array('365', '/uploads/userup/60/12X93O10-21E.pdf');
$maNum = 6;
$myaddons[$maNum] = array('366', '/uploads/userup/60/12X93R03-5210.pdf');
$maNum = 7;
