<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('833', '/uploads/userup/1/13193120L-D54.doc');
$maNum = 1;
$myaddons[$maNum] = array('834', '/uploads/userup/1/1319312109-J01.doc');
$maNum = 2;
$myaddons[$maNum] = array('835', '/uploads/userup/1/1319312249-2540.doc');
$maNum = 3;
$myaddons[$maNum] = array('836', '/uploads/userup/1/13193124a-ZX.doc');
$maNum = 4;
$myaddons[$maNum] = array('837', '/uploads/userup/1/1319312M6-bR.xls');
$maNum = 5;
$myaddons[$maNum] = array('838', '/uploads/userup/1/13193130D-1P3.xls');
$maNum = 6;
