<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('339', '/uploads/userup/1/12XB42O-3M1.doc');
$maNum = 1;
$myaddons[$maNum] = array('340', '/uploads/userup/1/12XB4316-9116.doc');
$maNum = 2;
$myaddons[$maNum] = array('341', '/uploads/userup/60/12XB5J7-5402.pdf');
$maNum = 3;
$myaddons[$maNum] = array('342', '/uploads/userup/60/12XB5923-Q47.pdf');
$maNum = 4;
$myaddons[$maNum] = array('343', '/uploads/userup/60/12XB59B-4321.pdf');
$maNum = 5;
$myaddons[$maNum] = array('344', '/uploads/userup/60/12XB6019-P95.pdf');
$maNum = 6;
$myaddons[$maNum] = array('345', '/uploads/userup/60/12XB6042-H03.pdf');
$maNum = 7;
