<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('532', '/uploads/userup/75/12913AR0-4261.pdf');
$maNum = 1;
$myaddons[$maNum] = array('533', '/uploads/userup/75/12913AU5-2J1.pdf');
$maNum = 2;
$myaddons[$maNum] = array('534', '/uploads/userup/75/12913AW2-5I3.pdf');
$maNum = 3;
$myaddons[$maNum] = array('535', '/uploads/userup/75/12913AX8-3221.pdf');
$maNum = 4;
$myaddons[$maNum] = array('536', '/uploads/userup/75/12913AZ5-2362.pdf');
$maNum = 5;
$myaddons[$maNum] = array('537', '/uploads/userup/75/12913A921-H03.pdf');
$maNum = 6;
$myaddons[$maNum] = array('538', '/uploads/userup/75/12913A947-5058.pdf');
$maNum = 7;
