<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('102', '/docshare/uploads/userup/8/12M53L95-51U.doc');
$maNum = 1;
$myaddons[$maNum] = array('103', '/docshare/uploads/userup/8/12M53MX-9415.doc');
$maNum = 2;
$myaddons[$maNum] = array('104', '/docshare/uploads/userup/8/12M53N37-b46.doc');
$maNum = 3;
$myaddons[$maNum] = array('105', '/docshare/uploads/userup/8/12M53NI-NP.doc');
$maNum = 4;
$myaddons[$maNum] = array('106', '/docshare/uploads/userup/8/12M53P23-9A6.doc');
$maNum = 5;
