<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('408', '/uploads/userup/60/12Y1U915-1Z8.pdf');
$maNum = 1;
$myaddons[$maNum] = array('409', '/uploads/userup/60/12Y1VS0-QT.pdf');
$maNum = 2;
$myaddons[$maNum] = array('410', '/uploads/userup/60/12Y1W115-T63.pdf');
$maNum = 3;
$myaddons[$maNum] = array('411', '/uploads/userup/60/12Y1W351-WV.pdf');
$maNum = 4;
$myaddons[$maNum] = array('412', '/uploads/userup/60/12Y1WC7-4160.pdf');
$maNum = 5;
$myaddons[$maNum] = array('413', '/uploads/userup/60/12Y1XR7-2S3.pdf');
$maNum = 6;
$myaddons[$maNum] = array('414', '/uploads/userup/60/12Y1Y4a-Q14.pdf');
$maNum = 7;
