<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('1103', '/uploads/userup/1/130454cV-2a7.pdf');
$maNum = 1;
$myaddons[$maNum] = array('1104', '/uploads/userup/1/13045501D-3N7.pdf');
$maNum = 2;
$myaddons[$maNum] = array('1105', '/uploads/userup/1/1304550296-HI.pdf');
$maNum = 3;
$myaddons[$maNum] = array('1106', '/uploads/userup/1/1304550316-P19.ppt');
$maNum = 4;
$myaddons[$maNum] = array('1107', '/uploads/userup/1/1304550a7-1X7.pdf');
$maNum = 5;
$myaddons[$maNum] = array('1108', '/uploads/userup/1/1304551030-b07.pdf');
$maNum = 6;
$myaddons[$maNum] = array('1109', '/uploads/userup/1/13045510I-2532.pdf');
$maNum = 7;
