<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('368', '/uploads/userup/61/12X944400-54U.ppt');
$maNum = 1;
$myaddons[$maNum] = array('372', '/uploads/userup/61/12X944O4-9533.ppt');
$maNum = 2;
$myaddons[$maNum] = array('373', '/uploads/userup/61/12X945003-4G2.ppt');
$maNum = 3;
$myaddons[$maNum] = array('374', '/uploads/userup/61/12X9455R-6019.doc');
$maNum = 4;
$myaddons[$maNum] = array('375', '/uploads/userup/61/12X945607-55G.doc');
$maNum = 5;
$myaddons[$maNum] = array('376', '/uploads/userup/61/12X946200-3606.doc');
$maNum = 6;
$myaddons[$maNum] = array('377', '/uploads/userup/61/12X946217-2131.doc');
$maNum = 7;
