<?php  exit();
/*
Page: /docshare/system/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/upload_book.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/upload_book.php
Error: No database selected <br />Error sql: <font color='red'>Select * From `t_member` where mid='1' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/upload_book.php
Error: No database selected <br />Error sql: <font color='red'>Select * From `t_member` where mid='1' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/upload_book.php
Error: No database selected <br />Error sql: <font color='red'>Select * From `t_member` where mid='1' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/upload_book.php
Error: No database selected <br />Error sql: <font color='red'>Select * From `t_member` where mid='1' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/upload_book.php
Error: No database selected <br />Error sql: <font color='red'>Select * From `t_member` where mid='1' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/upload_book.php
Error: No database selected <br />Error sql: <font color='red'>Select * From `t_member` where mid='1' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/upload_book.php
Error: No database selected <br />Error sql: <font color='red'>Select * From `t_member` where mid='1' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/upload_book.php
Error: No database selected <br />Error sql: <font color='red'>Select * From `t_member` where mid='1' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/view.php?aid=119
Error: Table 'docshare.dede_archives' doesn't exist <br />Error sql: <font color='red'>Select * from dede_archives where mid=1</font>
*/
?>
<?php  exit();
/*
Page: /docshare/mynews.php?aid=1
Error: Table 'docshare.dede_mynews' doesn't exist <br />Error sql: <font color='red'>Select * from dede_mynews where aid=1 limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/mynews.php?aid=1
Error: Table 'docshare.dede_mynews' doesn't exist <br />Error sql: <font color='red'>Select * from dede_mynews where aid=1 limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/mynews.php?aid=1
Error: Table 'docshare.dede_mynews' doesn't exist <br />Error sql: <font color='red'>Select * from dede_mynews where aid=1 limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/mynews.php?aid=1
Error: Table 'docshare.dede_mynews' doesn't exist <br />Error sql: <font color='red'>Select * from dede_mynews where aid=1 limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/mynews.php?aid=1
Error: Table 'docshare.dede_mynews' doesn't exist <br />Error sql: <font color='red'>Select * from dede_mynews where aid=1 limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/mynews.php?aid=1
Error: Table 'docshare.dede_mynews' doesn't exist <br />Error sql: <font color='red'>Select * from dede_mynews where aid=1 limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/mynews.php?aid=1
Error: Table 'docshare.dede_mynews' doesn't exist <br />Error sql: <font color='red'>Select * from dede_mynews where aid=1 limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/makehtml_homepage.php
Error: Table 'docshare.dede_member' doesn't exist <br />Error sql: <font color='red'>Select mid,userid,uname,face,scores From dede_member order by scores desc limit 0,2</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/view.php?aid=150
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4 <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		          tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		          from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		         where arc.arcrank>-1 and   arc.typeid in(44) And arc.id<>150   order by arc.id desc  limit 0, </font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/view.php?aid=150
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4 <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		          tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		          from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		         where arc.arcrank>-1 and   arc.typeid in(44) And arc.id<>150   order by arc.id desc  limit 0, </font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/view.php?aid=149
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4 <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		          tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		          from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		         where arc.arcrank>-1 and   arc.typeid in(57) And arc.id<>149   order by arc.id desc  limit 0, </font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/view.php?aid=150
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4 <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		          tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		          from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		         where arc.arcrank>-1 and   arc.typeid in(44) And arc.id<>150   order by arc.id desc  limit 0, </font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/view.php?aid=150
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4 <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		          tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		          from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		          where arc.arcrank>-1 and ( CONCAT(arc.keywords,' ',arc.title) like '%票面%'  OR CONCAT(arc.keywords,' ',arc.title) like '%中国人民%'  OR CONCAT(arc.keywords,' ',arc.title) like '%tttttttttttttasfasfasf%' )   And arc.typeid in(44) And arc.id<>150   order by arc.id desc  limit 0, </font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/view.php?aid=150
Error: Table 'docshare.dede_archives' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM dede_archives WHERE writer='倚地屠蛇'</font>
*/
?>
<?php  exit();
/*
Page: /docshare/list-mynews.php
Error: Table 'docshare.dede_mynews' doesn't exist <br />Error sql: <font color='red'>Select * from dede_mynews  order by senddate desc</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=tianya&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=like&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=tianya&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=like&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=like&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=tianya&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=tianya&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=like&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=tianya&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=like&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=tianya&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=tianya&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=like&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=2
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=5
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>

<?php  exit();
/*
Page: /docshare/member/ajax_loginsta.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/ajax_islogin.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=1
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/todaynewbooks.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=2
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=5
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=4
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=3
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/ajax_loginsta.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/ajax_islogin.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/todaynewbooks.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=2
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=1
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=3
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=4
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=5
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/ajax_loginsta.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/ajax_islogin.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/todaynewbooks.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=1
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=2
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=4
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=3
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/ad_js.php?aid=5
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/ajax_loginsta.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/ajax_islogin.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/disdls.php?aid=175
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/count.php?view=yes&aid=175&mid=1
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/disdls.php?aid=175
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/disstows.php?aid=175
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/bookdownloadusers.php?aid=175
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/ajax_feedback.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/feedback_ajax.php?dopost=getlist&aid=175&page=1
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/ajax_loginsta.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/download.php?open=2&id=175&uhash=102a3d77ef8733645e65a7ae
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /docshare/batchupload/index.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/batchupload/index.php?writer=admikn&mid=1&title=cctesttest&description=kltlsf&softurl1=/docshare/cctv/test.pdf
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/batchupload/index.php?writer=admikn&mid=1&title=cctesttest&description=kltlsf&softurl1=/docshare/cctv/test.pdf
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/batchupload/index.php?writer=admikn&mid=1&title=cctesttest&description=kltlsf&softurl1=/docshare/cctv/test.pdf
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/batchupload/index.php?writer=admikn&mid=1&title=cctesttest&description=kltlsf&softurl1=/docshare/cctv/test.pdf
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/batchupload/index.php?writer=admikn&mid=1&title=cctesttest&description=kltlsf&softurl1=/docshare/cctv/test.pdf
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '='17' and ispart = 0 limit 0,1' at line 1 <br />Error sql: <font color='red'>Select id From `t_arctype` channeltype='17' and ispart = 0 limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/interface/documentXML.php?aid=150
Error: Unknown column 'b.freepagenumber' in 'field list' <br />Error sql: <font color='red'>select a.title, a.writer, b.onlineviewurl, b.needmoney, b.pagenumber, b.freepagenumber from t_archives a, t_addonbook b where a.id = b.aid and a.id = '150' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/interface/documentXML.php?aid=150
Error: Unknown column 'b.freepagenumber' in 'field list' <br />Error sql: <font color='red'>select a.title, a.writer, b.onlineviewurl, b.needmoney, b.pagenumber, b.freepagenumber from t_archives a, t_addonbook b where a.id = b.aid and a.id = '150' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/interface/documentXML.php?aid=150
Error: Unknown column 'b.freepagenumber' in 'field list' <br />Error sql: <font color='red'>select a.title, a.writer, b.onlineviewurl, b.needmoney, b.pagenumber, b.freepagenumber from t_archives a, t_addonbook b where a.id = b.aid and a.id = '150' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/search.php?kwtype=0&keyword=cctv&searchtype=title
Error: Unknown column 'arc.arcrank' in 'where clause' <br />Error sql: <font color='red'>Select * From `t_addonspec` arc where  arc.arcrank > -1  And ( arc.title like '%cctv%' )</font>
*/
?>
<?php  exit();
/*
Page: /docshare/plus/search.php?kwtype=0&keyword=cctv&searchtype=title
Error: Unknown column 'arc.arcrank' in 'where clause' <br />Error sql: <font color='red'>Select arc.*,act.typedir,act.typename,act.isdefault,act.defaultname,act.namerule,
		act.namerule2,act.ispart,act.moresite,act.siteurl,act.sitepath
		from `t_addonspec` arc left join `t_arctype` act on arc.typeid=act.id
		where  arc.arcrank > -1  And ( arc.title like '%cctv%' ) order by arc.senddate desc limit 0,10</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/member_benefit.php?userid=cctv&imageField=%E6%90%9C%E7%B4%A2
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`t_member` b, where a.mid = b.mid and b.userid like '%cctv%' limit 0,1' at line 1 <br />Error sql: <font color='red'>Select count(*) as dd From `t_member_benefit` a `t_member` b, where a.mid = b.mid and b.userid like '%cctv%' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/member_benefit.php?userid=cctv&imageField=%E6%90%9C%E7%B4%A2
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`t_member` b, where a.mid = b.mid and b.userid like '%cctv%'  order by a.id desc' at line 1 <br />Error sql: <font color='red'>Select * From `t_member_benefit` a `t_member` b, where a.mid = b.mid and b.userid like '%cctv%'  order by a.id desc limit 0,25</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/member_benefit.php?userid=cc&imageField=%E6%90%9C%E7%B4%A2
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where a.mid = b.mid and b.userid like '%cc%' limit 0,1' at line 1 <br />Error sql: <font color='red'>Select count(*) as dd From `t_member_benefit` a , `t_member` b, where a.mid = b.mid and b.userid like '%cc%' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/member_benefit.php?userid=cc&imageField=%E6%90%9C%E7%B4%A2
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where a.mid = b.mid and b.userid like '%cc%'  order by a.id desc limit 0,25' at line 1 <br />Error sql: <font color='red'>Select * From `t_member_benefit` a , `t_member` b, where a.mid = b.mid and b.userid like '%cc%'  order by a.id desc limit 0,25</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/book_request_resp_docselect.php?respid=1
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/book_request_resp_docselect.php?respid=1
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/book_request_resp.php?reqid=56
Error: Unknown column 'b.uname' in 'field list' <br />Error sql: <font color='red'>Select a.*, b.uname from `t_member_request` a, `t_member_request` b where a.mid = b.mid and id='56' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/book_request_resp.php?reqid=56
Error: Column 'id' in where clause is ambiguous <br />Error sql: <font color='red'>Select * from `t_member_request` a, `t_member_request` where id='56' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=tianya&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=like&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=tianya&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=ccav&action=archives&channelid=17
Error: Unknown column 'arc.mid' in 'where clause' <br />Error sql: <font color='red'>Select count(*) as dd From `t_addonbook` arc 
			       left join `t_arctype` tp on arc.typeid=tp.id
		         where arc.mid='35' And arc.channel='17'  order by arc.aid desc limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=ccav&action=archives&channelid=17
Error: Unknown column 'arc.mid' in 'where clause' <br />Error sql: <font color='red'>Select arc.aid,arc.aid as id,arc.typeid,'' as mtypename,1 as ismake,0 as money,'' as filename,arc.filetype,arc.language,arc.softtype,arc.accredit,arc.os,arc.softrank,arc.daccess,arc.needmoney,arc.pagenumber,
			       tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			       from `t_addonbook` arc 
			       left join `t_arctype` tp on arc.typeid=tp.id
		         where arc.mid='35' And arc.channel='17'  order by arc.aid desc limit 0,10</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=ccav&action=archives&channelid=17
Error: Unknown column 'arc.mid' in 'where clause' <br />Error sql: <font color='red'>Select count(*) as dd From `t_addonbook` arc 
			       left join `t_arctype` tp on arc.typeid=tp.id
		         where arc.mid='35' And arc.channel='17'  order by arc.aid desc limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /docshare/member/index.php?uid=ccav&action=archives&channelid=17
Error: Unknown column 'arc.mid' in 'where clause' <br />Error sql: <font color='red'>Select arc.aid,arc.aid as id,arc.typeid,'' as mtypename,1 as ismake,0 as money,'' as filename,arc.filetype,arc.language,arc.softtype,arc.accredit,arc.os,arc.softrank,arc.daccess,arc.needmoney,arc.pagenumber,
			       tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			       from `t_addonbook` arc 
			       left join `t_arctype` tp on arc.typeid=tp.id
		         where arc.mid='35' And arc.channel='17'  order by arc.aid desc limit 0,10</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/sys_info.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where modify = 0 order by aid asc' at line 1 <br />Error sql: <font color='red'>Select * From `t_sysconfig` where groupid='1' where modify = 0 order by aid asc</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/sys_info.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where modify = 0 order by aid asc' at line 1 <br />Error sql: <font color='red'>Select * From `t_sysconfig` where groupid='2' where modify = 0 order by aid asc</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/sys_info.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where modify = 0 order by aid asc' at line 1 <br />Error sql: <font color='red'>Select * From `t_sysconfig` where groupid='3' where modify = 0 order by aid asc</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/sys_info.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where modify = 0 order by aid asc' at line 1 <br />Error sql: <font color='red'>Select * From `t_sysconfig` where groupid='4' where modify = 0 order by aid asc</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/sys_info.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where modify = 0 order by aid asc' at line 1 <br />Error sql: <font color='red'>Select * From `t_sysconfig` where groupid='5' where modify = 0 order by aid asc</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/sys_info.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where modify = 0 order by aid asc' at line 1 <br />Error sql: <font color='red'>Select * From `t_sysconfig` where groupid='6' where modify = 0 order by aid asc</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/sys_info.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where modify = 0 order by aid asc' at line 1 <br />Error sql: <font color='red'>Select * From `t_sysconfig` where groupid='7' where modify = 0 order by aid asc</font>
*/
?>
<?php  exit();
/*
Page: /docshare/system/sys_info.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where modify = 0 order by aid asc' at line 1 <br />Error sql: <font color='red'>Select * From `t_sysconfig` where groupid='8' where modify = 0 order by aid asc</font>
*/
?>
<?php  exit();
/*
Page: /member/inc/uploadify.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/inc/uploadify.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/inc/uploadify.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/inc/uploadify.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/inc/uploadify.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/inc/uploadify.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?action=archives&uid=admin
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?action=archives&channelid=17&uid=admin
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?action=archives&uid=admin
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?action=archives&channelid=17&uid=admin
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/inc/uploadify.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=0&typeid=0&totalnum=78&startdd=20&pagesize=20&seltime=0&sstime=1292820232&stime=&etime=&uptype=mkall&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=78&startdd=20&pagesize=20&seltime=0&sstime=1292820475&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=0&typeid=0&totalnum=78&startdd=20&pagesize=20&seltime=0&sstime=1292825804&stime=&etime=&uptype=mkall&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=0&typeid=0&totalnum=89&startdd=20&pagesize=20&seltime=0&sstime=1292827075&stime=&etime=&uptype=mkall&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=-1&typeid=17&totalnum=100&startdd=20&pagesize=20&seltime=0&sstime=1292917234&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=0&typeid=0&totalnum=100&startdd=20&pagesize=20&seltime=0&sstime=1292917309&stime=&etime=&uptype=mkall&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=100&startdd=20&pagesize=20&seltime=0&sstime=1292917559&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=112&startdd=20&pagesize=20&seltime=0&sstime=1293240837&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=0&typeid=0&totalnum=112&startdd=20&pagesize=20&seltime=0&sstime=1293240920&stime=&etime=&uptype=mkall&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/catalog_main.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/inc/uploadify.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit 0,1' at line 1 <br />Error sql: <font color='red'>Select aid,title,url From `t_uploads` where aid =  limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?action=archives&channelid=17&uid=admin
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?action=archives&channelid=17&uid=admin
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=100&startdd=80&pagesize=20&seltime=0&sstime=1298235227&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=100&startdd=80&pagesize=20&seltime=0&sstime=1298246173&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=0&typeid=0&totalnum=100&startdd=80&pagesize=20&seltime=0&sstime=1298246477&stime=&etime=&uptype=mkall&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=100&startdd=80&pagesize=20&seltime=0&sstime=1298246515&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=0&typeid=0&totalnum=115&startdd=80&pagesize=20&seltime=0&sstime=1298328108&stime=&etime=&uptype=mkall&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /plus/view.php?aid=87
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /plus/bookdownloadusers.php?aid=118
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=0&typeid=0&totalnum=120&startdd=80&pagesize=20&seltime=0&sstime=1298368585&stime=&etime=&uptype=mkall&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=132&startdd=80&pagesize=20&seltime=0&sstime=1298411769&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=132&startdd=80&pagesize=20&seltime=0&sstime=1298412388&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /plus/view.php?aid=144
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /plus/view.php?aid=144
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /system/login.php?gotopage=%2Fsystem%2Findex.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/view.php?aid=144
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /plus/view.php?aid=145
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /plus/view.php?aid=144
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /plus/stow.php?aid=132
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/view.php?aid=144
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /plus/view.php?aid=145
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /plus/view.php?aid=145
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~ order by click desc limit 0, 20' at line 1 <br />Error sql: <font color='red'>SELECT * FROM t_archives WHERE writer=~writer~ order by click desc limit 0, 20</font>
*/
?>
<?php  exit();
/*
Page: /plus/erraddsave.php?aid=202&title=%E6%88%BF%E5%9C%B0%E4%BA%A7%E8%90%A5%E9%94%80%E8%AE%A1%E5%88%92.doc
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/erraddsave.php?aid=351&title=%E5%98%89%E5%88%A9%E8%8A%B1%E5%9B%AD%E6%8E%A8%E5%B9%BF%E6%96%87%E6%A1%88.doc
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?action=archives&uid=admin
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /plus/view.php?aid=448
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/erraddsave.php?aid=60&title=%E2%80%9C%E5%8F%A4%E6%B1%89%E5%85%BB%E7%94%9F%E7%B2%BE%E2%80%9D%E4%B8%8A%E6%B5%B7%E5%B8%82%E5%9C%BA%E8%90%A5%E9%94%80%E7%AD%96%E5%88%92%E6%A1%88.doc
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /tags.php?/.PPT/-487/
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/count.php?aid=183&mid=61&view=yes
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?action=archives&channelid=17&uid=admin
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?action=archives&channelid=17&uid=admin
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=401
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/view.php?aid=234
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=313
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/interface/documentXML.php?aid=540
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/ajax_loginsta.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=77
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/count.php?view=yes&aid=77&mid=60
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=77
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/disstows.php?aid=77
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/bookdownloadusers.php?aid=77
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/ajax_feedback.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/feedback_ajax.php?dopost=getlist&aid=77&page=1
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/ajax_loginsta.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/interface/documentXML.php?aid=77
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /system/content_list.php?cid=17
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=157
Error: Table 't_downloads' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select sum(downloads) as totals From `t_downloads`  where id='157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/count.php?view=yes&aid=157&mid=99
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select click From `t_archives`  where id='157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=157
Error: Table 't_downloads' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select sum(downloads) as totals From `t_downloads`  where id='157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disstows.php?aid=157
Error: Table 't_member_stow' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select count(1) as totals From `t_member_stow`  where aid='157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/bookdownloadusers.php?aid=157
Error: Table 't_member_download' is marked as crashed and should be repaired <br />Error sql: <font color='red'>select distinct b.userid userid from t_member_download a, t_member b where a.mid = b.mid and a.aid = '157';</font>
*/
?>
<?php  exit();
/*
Page: /member/interface/documentXML.php?aid=157
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>select a.title, a.writer, b.onlineviewurl, b.needmoney, b.pagenumber, b.pagenumber2 from t_archives a, t_addonbook b where a.id = b.aid and a.id = '157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=157
Error: Table 't_downloads' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select sum(downloads) as totals From `t_downloads`  where id='157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/count.php?view=yes&aid=157&mid=99
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select click From `t_archives`  where id='157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=157
Error: Table 't_downloads' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select sum(downloads) as totals From `t_downloads`  where id='157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disstows.php?aid=157
Error: Table 't_member_stow' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select count(1) as totals From `t_member_stow`  where aid='157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/bookdownloadusers.php?aid=157
Error: Table 't_member_download' is marked as crashed and should be repaired <br />Error sql: <font color='red'>select distinct b.userid userid from t_member_download a, t_member b where a.mid = b.mid and a.aid = '157';</font>
*/
?>
<?php  exit();
/*
Page: /member/interface/documentXML.php?aid=157
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>select a.title, a.writer, b.onlineviewurl, b.needmoney, b.pagenumber, b.pagenumber2 from t_archives a, t_addonbook b where a.id = b.aid and a.id = '157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=56
Error: Table 't_downloads' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select sum(downloads) as totals From `t_downloads`  where id='56' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/count.php?view=yes&aid=56&mid=62
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select click From `t_archives`  where id='56' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=56
Error: Table 't_downloads' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select sum(downloads) as totals From `t_downloads`  where id='56' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disstows.php?aid=56
Error: Table 't_member_stow' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select count(1) as totals From `t_member_stow`  where aid='56' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/bookdownloadusers.php?aid=56
Error: Table 't_member_download' is marked as crashed and should be repaired <br />Error sql: <font color='red'>select distinct b.userid userid from t_member_download a, t_member b where a.mid = b.mid and a.aid = '56';</font>
*/
?>
<?php  exit();
/*
Page: /member/interface/documentXML.php?aid=56
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>select a.title, a.writer, b.onlineviewurl, b.needmoney, b.pagenumber, b.pagenumber2 from t_archives a, t_addonbook b where a.id = b.aid and a.id = '56' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=27
Error: Table 't_downloads' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select sum(downloads) as totals From `t_downloads`  where id='27' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=27
Error: Table 't_downloads' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select sum(downloads) as totals From `t_downloads`  where id='27' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disstows.php?aid=27
Error: Table 't_member_stow' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select count(1) as totals From `t_member_stow`  where aid='27' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/bookdownloadusers.php?aid=27
Error: Table 't_member_download' is marked as crashed and should be repaired <br />Error sql: <font color='red'>select distinct b.userid userid from t_member_download a, t_member b where a.mid = b.mid and a.aid = '27';</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=31
Error: Table 't_downloads' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select sum(downloads) as totals From `t_downloads`  where id='31' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=31
Error: Table 't_downloads' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select sum(downloads) as totals From `t_downloads`  where id='31' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disstows.php?aid=31
Error: Table 't_member_stow' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select count(1) as totals From `t_member_stow`  where aid='31' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/bookdownloadusers.php?aid=31
Error: Table 't_member_download' is marked as crashed and should be repaired <br />Error sql: <font color='red'>select distinct b.userid userid from t_member_download a, t_member b where a.mid = b.mid and a.aid = '31';</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=157
Error: Table 't_downloads' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select sum(downloads) as totals From `t_downloads`  where id='157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/count.php?view=yes&aid=157&mid=99
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select click From `t_archives`  where id='157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disdls.php?aid=157
Error: Table 't_downloads' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select sum(downloads) as totals From `t_downloads`  where id='157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/disstows.php?aid=157
Error: Table 't_member_stow' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select count(1) as totals From `t_member_stow`  where aid='157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/bookdownloadusers.php?aid=157
Error: Table 't_member_download' is marked as crashed and should be repaired <br />Error sql: <font color='red'>select distinct b.userid userid from t_member_download a, t_member b where a.mid = b.mid and a.aid = '157';</font>
*/
?>
<?php  exit();
/*
Page: /member/interface/documentXML.php?aid=157
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>select a.title, a.writer, b.onlineviewurl, b.needmoney, b.pagenumber, b.pagenumber2 from t_archives a, t_addonbook b where a.id = b.aid and a.id = '157' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/index_do.php
Error: Incorrect key file for table '.\docshare\t_member.MYI'; try to repair it <br />Error sql: <font color='red'>Select mid,matt,pwd,logintime From `t_member` where userid like 'zhangyunzhou' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/index_do.php
Error: Incorrect key file for table '.\docshare\t_member.MYI'; try to repair it <br />Error sql: <font color='red'>Select mid,matt,pwd,logintime From `t_member` where userid like 'zhangyunzhou' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/index_do.php
Error: Incorrect key file for table '.\docshare\t_member.MYI'; try to repair it <br />Error sql: <font color='red'>Select mid,matt,pwd,logintime From `t_member` where userid like 'zhangyunzhou' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/index_do.php
Error: Incorrect key file for table '.\docshare\t_member.MYI'; try to repair it <br />Error sql: <font color='red'>Select * From `t_member` where userid like 'zhangyunzhou1' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/index_do.php
Error: Incorrect key file for table '.\docshare\t_member.MYI'; try to repair it <br />Error sql: <font color='red'>Select * From `t_member` where userid like 'zhangyunzhou1' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/content_list.php?channelid=17
Error: Lost connection to MySQL server during query <br />Error sql: <font color='red'>Select count(*) as dd From `t_archives` arc
        left join `t_arctype` tp on tp.id=arc.typeid
        left join `t_channeltype` ch on ch.id=arc.channel
        where arc.channel = '17' And arc.mid='99' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php
Error: Lost connection to MySQL server during query <br />Error sql: <font color='red'>select arc.*, category.namerule, category.typedir, category.moresite, category.siteurl, category.sitepath, mem.userid
		from t_archives arc
		left join t_arctype category on category.id=arc.typeid
		left join t_member mem on mem.mid=arc.mid
		where arc.arcrank > -1
		order by arc.sortrank desc limit 8</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php
Error: MySQL server has gone away <br />Error sql: <font color='red'>Select * From `t_member_stow` where mid='99'  limit 5</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php
Error: MySQL server has gone away <br />Error sql: <font color='red'>SELECT * FROM `t_member` ORDER BY mid desc limit 3</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php
Error: MySQL server has gone away <br />Error sql: <font color='red'>SELECT F.*,M.face,M.sex FROM `t_member` AS M LEFT JOIN t_member_friends AS F ON F.fid=M.mid WHERE F.mid='99' ORDER BY F.addtime desc LIMIT 6</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php
Error: MySQL server has gone away <br />Error sql: <font color='red'>SELECT COUNT(*) AS nums FROM t_member_pms WHERE toid='99' AND `hasview`=0 AND folder = 'inbox' limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php
Error: MySQL server has gone away <br />Error sql: <font color='red'>SELECT * FROM t_member_msg WHERE mid='99' ORDER BY dtime desc limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php
Error: MySQL server has gone away <br />Error sql: <font color='red'>SELECT * From `t_member_feed` where ischeck=1 order by fid desc limit 8</font>
*/
?>
<?php  exit();
/*
Page: /member/content_list.php?channelid=17
Error: MySQL server has gone away <br />Error sql: <font color='red'>select arc.id,arc.typeid,arc.senddate,arc.flag,arc.ismake,arc.channel,arc.arcrank,
        arc.click,arc.title,arc.color,arc.litpic,arc.pubdate,arc.mid,tp.typename,ch.typename as channelname
        from `t_archives` arc
        left join `t_arctype` tp on tp.id=arc.typeid
        left join `t_channeltype` ch on ch.id=arc.channel
        where arc.channel = '17' And arc.mid='99'  order by arc.senddate desc  limit 0,20</font>
*/
?>
<?php  exit();
/*
Page: /member/content_list.php?channelid=17
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/ajax_loginsta.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/ajax_loginsta.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: Table 't_archives' is marked as crashed and should be repaired <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: No database selected <br />Error sql: <font color='red'>SELECT count( * ) AS totals FROM t_archives WHERE pubdate > UNIX_TIMESTAMP( CURDATE( ) ) limit 0,1;</font>
*/
?>
<?php  exit();
/*
Page: /system/member_type.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/todaynewbooks.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/login.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /member/ajax_loginsta.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Unknown column 'addf.totalpagenumber' in 'field list' <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		,addf.filetype,addf.totalpagenumber
		from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		 left join `t_addonbook` addf on addf.aid = arc.id 
		 where  arc.typeid in (17) And  arc.channel = '17'  And  FIND_IN_SET('h', arc.flag)<1  And  arc.arcrank > -1    order by arc.sortrank desc  limit 0,5 </font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Unknown column 'addf.totalpagenumber' in 'field list' <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		,addf.filetype,addf.totalpagenumber
		from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		 left join `t_addonbook` addf on addf.aid = arc.id 
		 where  arc.typeid in (85) And  arc.channel = '17'  And  FIND_IN_SET('h', arc.flag)<1  And  arc.arcrank > -1    order by arc.sortrank desc  limit 0,5 </font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Unknown column 'addf.totalpagenumber' in 'field list' <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		,addf.filetype,addf.totalpagenumber
		from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		 left join `t_addonbook` addf on addf.aid = arc.id 
		 where  arc.typeid in (17) And  arc.channel = '17'  And  FIND_IN_SET('h', arc.flag)<1  And  arc.arcrank > -1    order by arc.sortrank desc  limit 0,5 </font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Unknown column 'addf.totalpagenumber' in 'field list' <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		,addf.filetype,addf.totalpagenumber
		from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		 left join `t_addonbook` addf on addf.aid = arc.id 
		 where  arc.typeid in (85) And  arc.channel = '17'  And  FIND_IN_SET('h', arc.flag)<1  And  arc.arcrank > -1    order by arc.sortrank desc  limit 0,5 </font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Unknown column 'addf.totalpagenumber' in 'field list' <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		,addf.filetype,addf.totalpagenumber
		from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		 left join `t_addonbook` addf on addf.aid = arc.id 
		 where  arc.typeid in (17) And  arc.channel = '17'  And  FIND_IN_SET('h', arc.flag)<1  And  arc.arcrank > -1    order by arc.sortrank desc  limit 0,5 </font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Unknown column 'addf.totalpagenumber' in 'field list' <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		,addf.filetype,addf.totalpagenumber
		from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		 left join `t_addonbook` addf on addf.aid = arc.id 
		 where  arc.typeid in (85) And  arc.channel = '17'  And  FIND_IN_SET('h', arc.flag)<1  And  arc.arcrank > -1    order by arc.sortrank desc  limit 0,5 </font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Unknown column 'addf.totalpagenumber' in 'field list' <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		,addf.filetype,addf.totalpagenumber
		from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		 left join `t_addonbook` addf on addf.aid = arc.id 
		 where  arc.typeid in (17) And  arc.channel = '17'  And  FIND_IN_SET('h', arc.flag)<1  And  arc.arcrank > -1    order by arc.sortrank desc  limit 0,5 </font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Unknown column 'addf.totalpagenumber' in 'field list' <br />Error sql: <font color='red'>Select arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
		tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		,addf.filetype,addf.totalpagenumber
		from `t_archives` arc left join `t_arctype` tp on arc.typeid=tp.id
		 left join `t_addonbook` addf on addf.aid = arc.id 
		 where  arc.typeid in (85) And  arc.channel = '17'  And  FIND_IN_SET('h', arc.flag)<1  And  arc.arcrank > -1    order by arc.sortrank desc  limit 0,5 </font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Table 'docshare.wenku_downloads' doesn't exist <br />Error sql: <font color='red'>select A.id,A.title,D.downloads from wenku_downloads as D left join wenku_archives as A ON D.id = A.id WHERE pubdate > UNIX_TIMESTAMP( CURDATE() - INTERVAL 1 day) order by downloads DESC limit 0,10;</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Table 'docshare.wenku_downloads' doesn't exist <br />Error sql: <font color='red'>select A.id,A.title,D.downloads from wenku_downloads as D left join wenku_archives as A ON D.id = A.id WHERE pubdate > UNIX_TIMESTAMP( CURDATE() - INTERVAL 7 day) order by downloads DESC limit 0,10;</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Table 'docshare.wenku_downloads' doesn't exist <br />Error sql: <font color='red'>select A.id,A.title,D.downloads from wenku_downloads as D left join wenku_archives as A ON D.id = A.id WHERE pubdate > UNIX_TIMESTAMP( CURDATE() - INTERVAL 30 day) order by downloads DESC limit 0,10;</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives&channelid=17
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
			        from `t_archives` arc
			        left join `t_arctype` tp on arc.typeid=tp.id
			        left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid='' And arc.channel='17'  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /member/index.php?uid=admin&action=archives
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5 <br />Error sql: <font color='red'>Select arc.*,mt.mtypename,tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
		         from `t_archives` arc 
		         left join `t_arctype` tp on arc.typeid=tp.id
		         left join `t_mtypes` mt on mt.mtypeid=arc.mtype
		         where arc.mid=''  order by arc.id desc limit 0,</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'form `t_member` where rank>=100' at line 1 <br />Error sql: <font color='red'>select count(mid) as dd form `t_member` where rank>=100</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'form `t_member` where rank>=100' at line 1 <br />Error sql: <font color='red'>select count(mid) as dd form `t_member` where rank>=100</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'form `t_member` where rank>=100' at line 1 <br />Error sql: <font color='red'>select count(mid) as dd form `t_member` where rank>=100</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'form `t_member` where rank>=100' at line 1 <br />Error sql: <font color='red'>select count(mid) as dd form `t_member` where rank>=100</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'form `t_member` where rank>=100' at line 1 <br />Error sql: <font color='red'>select count(*) as dd form `t_member` where rank>=100</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'form `t_member` where rank>=100' at line 1 <br />Error sql: <font color='red'>select count(*) as dd form `t_member` where rank>=100</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'form `t_member` where rank>=100' at line 1 <br />Error sql: <font color='red'>select count(*) as dd form `t_member` where rank>=100</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'form t_member where rank>=100' at line 1 <br />Error sql: <font color='red'>select count(*) as dd form t_member where rank>=100</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'form t_member where rank>=100' at line 1 <br />Error sql: <font color='red'>select count(*) as dd form t_member where rank>=100</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'form t_member where rank>=100' at line 1 <br />Error sql: <font color='red'>select count(*) as dd form t_member where rank>=100</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'form t_member where rank>=100' at line 1 <br />Error sql: <font color='red'>select count(mid) as dd form t_member where rank>=100</font>
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'form t_member where rank>=100' at line 1 <br />Error sql: <font color='red'>select count(mid) as dd form t_member where rank>=100</font>
*/
?>
<?php  exit();
/*
Page: /member/ajax_loginsta.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
